In [3]:
import numpy as npi

yufan= npi.array([1,2,3,4,5])
print (yufan)



a=npi.array([[[1,4,3],[1,2,7],[3,8,8]],[[1,2,3],[3,4,5],[4,5,8]],[[1,9,0],[1,5,4],[7,6,9]]])
b=npi.array([[[3,4,5],[6,8,2],[5,4,6]],[[8,2,6],[7,3,9],[8,5,4]],[[7,6,5],[9,5,5],[2,8,4]]])

c=a+b
print(a)
print(b)
print(c)

[1 2 3 4 5]
[[[1 4 3]
  [1 2 7]
  [3 8 8]]

 [[1 2 3]
  [3 4 5]
  [4 5 8]]

 [[1 9 0]
  [1 5 4]
  [7 6 9]]]
[[[3 4 5]
  [6 8 2]
  [5 4 6]]

 [[8 2 6]
  [7 3 9]
  [8 5 4]]

 [[7 6 5]
  [9 5 5]
  [2 8 4]]]
[[[ 4  8  8]
  [ 7 10  9]
  [ 8 12 14]]

 [[ 9  4  9]
  [10  7 14]
  [12 10 12]]

 [[ 8 15  5]
  [10 10  9]
  [ 9 14 13]]]
